spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/api-jva-security-users
    username: postgres
    password: 3005
    driver-class-name: org.postgresql.Driver
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8090/eureka
